version: "3.9"

services:
  app:
    build: .
    container_name: event-analyzer
    ports:
      - "8505:8505"
    volumes:
      - ./models:/app/models
    command: poetry run streamlit run app/home.py --server.port=8505
